---
title: "Research Questions"
author: "Lauryl Zenobi"
date: "April 8, 2015"
output: html_document
---
<p>For the purpose of this quantitative project I want to explore the relationship between several sets of words. This quantitative data will be used to improve upon the background and theoretical framework of my dissertation proposal. There is also the potential that this data will provide methodological approaches to the quantitative portion of my dissertation research. </p>

<p>Questions that I think would be well-suited to this type of research are listed below.</p>
1. What is the relationships between standardization and ceramics in the archaeological literature? Has this relationship changed over time? What theoretical frameworks support these types of analyses?
2. What is the relationship between sago palm and ceramic analyses in Indonesia? Specifically, what is the statistical relationship between the use of terms such as sago, sago starch, ceramics, and forna (ceramic ovens) in the archaeological literature?
3. What is the relationship between theories about colonial contact and acculturation and changes in ceramic assemblages? Specifically for Indonesia, how do these topics present in the archaeological literature?
4. How has the spice trade and the sago trade been analyzed in the archaeological literature? What is the relationship between terms such as spice trade, nutmeg, cloves, and sago? 

<p>Due to the small sample size that is expected for these topics and study area, this project will consists of two parts. The first is a statistical analysis of the frequency of the terms identified in the preceding questions. The second part will consist of a close reading of selected articles of interest. The low numbers expected from the statistical analysis necessitate the close readings, which will be beneficial in answering higher level questions about the theoretical frameworks that were utilized in the articles of interest. </p>


<p>Codes from the JSTORr package will be utilized for the statistical analysis. Potential codes include the following:</p>
<pre code>
<p>JSTOR_2words(multiple_archives, "sago", "ceramics")</p>
<p>JSTOR_2wordcor(multiple_archives, "sago", "forna")</p>
<p>JSTOR_findassocs(multiple_archives, Vector of terms, "sago")</p>
</pre code>

